// Generated by typings
// Source: https://raw.githubusercontent.com/simonwoodhead/DefinitelyTyped/74f5915ca943efec59d237f5a4235c58827dc9eb/react-tap-event-plugin/react-tap-event-plugin.d.ts
declare module 'react-tap-event-plugin'{
    interface StrategyOverrides {
        shouldRejectClick?: (lastTouchEventTimestamp: Date, clickEventTimestamp: Date) => boolean;
    }

    var injectTapEventPlugin: (strategyOverrides?: StrategyOverrides) => void;

    export default injectTapEventPlugin;
}